{{- if .Values.secretEnvs }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.applicationName }}-secret
  namespace: {{ $.Values.applicationName }}
type: generic
data:
  {{- range $key,$val := .Values.secretEnvs }}
  {{$key}}: {{$val | b64enc | quote}}
  {{- end}}
{{- end}}
